### ISSUE TITLE
FKgk님! 이메일 한번만 확인 부탁드립니다 :)

### ISSUE THREAD

**Issue by jihun-ko** [FKgk/BOJ#2]
안녕하세요! 저는 뤼이드에서 백엔드 엔지니어로 근무중인 고지훈이라고 합니다.
링크드인에서 1촌이 아니어서 프로필을 확인을 못하는 바람에 유일하게 연락할 창구인 github으로 연락드립니다.

확인하시고 메일 답장 부탁드립니다 :)
(확인하시는대로 이슈는 닫겠습니다.)

**Comment by FKgk** [comment]
안녕하세요 lopun님
저에게 관심을 가지고 메일까지 보내주셔서 감사합니다.
곧 메일 답장을 보내드리도록 하겠습니다.
감사합니다 :)

**Comment by jihun-ko** [comment]
감사합니다! :)
엔지니어분들은(특히 보충역분들은) 정말 성심성의껏 모시고 있으니 많은 관심 부탁드립니다 🙏
